// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace aspNet.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20220929064832_ColumnApellidosAlumno")]
    partial class ColumnApellidosAlumno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aspNet.Models.Alumno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CursoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = "002b8121-6658-4795-b142-a5dc8fc666d9",
                            Apellidos = "Maduro",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Nicolás Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "00a4be34-bfa4-444c-9a46-15956492182d",
                            Apellidos = "Ruiz",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Farid Silvana Ruiz"
                        },
                        new
                        {
                            Id = "01817dbf-b205-4d3c-9417-ca2ed8839287",
                            Apellidos = "Ruiz",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Donald Anabel Ruiz"
                        },
                        new
                        {
                            Id = "01ccdb69-b9a4-41cb-af36-545cb170d425",
                            Apellidos = "Sarmiento",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Alvaro Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "01de8f3a-e0b4-47b2-bb7e-fd4dcab048bd",
                            Apellidos = "Trump",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Farid Murty Trump"
                        },
                        new
                        {
                            Id = "02d282aa-5fd7-4b84-b7e9-a5ad8625bde1",
                            Apellidos = "Maduro",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Farid Silvana Maduro"
                        },
                        new
                        {
                            Id = "02ed0930-835b-405f-a9b5-765898070dfc",
                            Apellidos = "Maduro",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Felipa Diomedes Maduro"
                        },
                        new
                        {
                            Id = "01eb5c11-8ec8-4a27-8aad-da359477806a",
                            Apellidos = "Ruiz",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Farid Silvana Ruiz"
                        },
                        new
                        {
                            Id = "0279901d-9218-45fc-a009-3ad2fd734e4e",
                            Apellidos = "Toledo",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Nicolás Teodoro Toledo"
                        },
                        new
                        {
                            Id = "03bdce0e-9325-4740-8e34-30261b0ced55",
                            Apellidos = "Maduro",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Felipa Rick Maduro"
                        },
                        new
                        {
                            Id = "04f910b8-7f27-436b-b474-51ba21299bf3",
                            Apellidos = "Herrera",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Felipa Rick Herrera"
                        },
                        new
                        {
                            Id = "055b33a6-2e61-45d7-b481-1573f2fc45de",
                            Apellidos = "Uribe",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Nicolás Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "079609b3-6456-4c3b-b1d7-454e5049f6ac",
                            Apellidos = "Toledo",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Eusebio Murty Toledo"
                        },
                        new
                        {
                            Id = "081fb7ef-e3a3-4e79-85e6-23f329e18234",
                            Apellidos = "Ruiz",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Donald Silvana Ruiz"
                        },
                        new
                        {
                            Id = "086de150-8434-4c26-84bc-4e0650288771",
                            Apellidos = "Trump",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Felipa Diomedes Trump"
                        },
                        new
                        {
                            Id = "088aa541-e4c3-4583-a7cd-b955767ac1ea",
                            Apellidos = "Uribe",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Felipa Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "088cc3d0-2e5a-43f5-a1ef-466ad384fcd9",
                            Apellidos = "Toledo",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Eusebio Anabel Toledo"
                        },
                        new
                        {
                            Id = "08aed684-09a7-4427-a311-fb74fbec612b",
                            Apellidos = "Herrera",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Donald Freddy Herrera"
                        },
                        new
                        {
                            Id = "090a1516-f536-4119-a998-ecacc111291b",
                            Apellidos = "Sarmiento",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Donald Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "0ae4b832-27cb-4386-a111-5c4dfbfa4120",
                            Apellidos = "Uribe",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Alvaro Anabel Uribe"
                        },
                        new
                        {
                            Id = "0b24fe82-f199-4328-8962-0882d0f30643",
                            Apellidos = "Trump",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Donald Diomedes Trump"
                        },
                        new
                        {
                            Id = "017452bb-869b-4af3-92a6-c2bf246d6f4a",
                            Apellidos = "Uribe",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Nicolás Anabel Uribe"
                        },
                        new
                        {
                            Id = "0307222d-8fd5-428f-9bbe-965b972791e0",
                            Apellidos = "Trump",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Nicolás Freddy Trump"
                        },
                        new
                        {
                            Id = "04d494a6-e36b-4f65-b2aa-31d551c2f267",
                            Apellidos = "Ruiz",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Felipa Murty Ruiz"
                        },
                        new
                        {
                            Id = "0500ae66-f7e3-42bc-92ae-d3c62892fe59",
                            Apellidos = "Uribe",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Donald Silvana Uribe"
                        },
                        new
                        {
                            Id = "060cef03-b423-442d-aec3-c0435a94aafb",
                            Apellidos = "Ruiz",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Alvaro Rick Ruiz"
                        },
                        new
                        {
                            Id = "06aa4adf-6e76-49c4-8cac-a3a19484b07a",
                            Apellidos = "Trump",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Alba Teodoro Trump"
                        },
                        new
                        {
                            Id = "0726d320-d110-4608-a9c0-5a9284b9176f",
                            Apellidos = "Uribe",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Farid Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "07580047-6ae6-4350-977c-1991ab27ce6e",
                            Apellidos = "Sarmiento",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Alvaro Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "0776aa88-cb3a-4e81-99e4-4e02e6c4dbbe",
                            Apellidos = "Maduro",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Alba Murty Maduro"
                        },
                        new
                        {
                            Id = "079cdb73-f4e4-44ee-b86a-d8b01d77716a",
                            Apellidos = "Toledo",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Alvaro Rick Toledo"
                        },
                        new
                        {
                            Id = "07b4c392-d097-436c-b955-3817ff805bde",
                            Apellidos = "Toledo",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Alba Teodoro Toledo"
                        },
                        new
                        {
                            Id = "07f5db1b-f2db-44b9-b99a-0fc945f4b6cc",
                            Apellidos = "Maduro",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Eusebio Murty Maduro"
                        },
                        new
                        {
                            Id = "09de98dc-1be5-487a-9df0-439f9fa694e1",
                            Apellidos = "Herrera",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Alvaro Silvana Herrera"
                        },
                        new
                        {
                            Id = "0008fa96-946a-4d77-b5b9-cf4438e52fd9",
                            Apellidos = "Herrera",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Farid Teodoro Herrera"
                        },
                        new
                        {
                            Id = "000e35c7-14e9-48b4-8aa0-61a6e43f6fe1",
                            Apellidos = "Ruiz",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Alvaro Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "025aa5a0-804e-47ca-b037-667ac90c0b14",
                            Apellidos = "Herrera",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Alba Anabel Herrera"
                        },
                        new
                        {
                            Id = "025c9f72-35a5-4719-be86-3516de0ff683",
                            Apellidos = "Maduro",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Farid Murty Maduro"
                        },
                        new
                        {
                            Id = "02647871-a8fc-4e59-be77-ae71926fffca",
                            Apellidos = "Toledo",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Eusebio Murty Toledo"
                        },
                        new
                        {
                            Id = "03153900-b475-48a9-9358-a2595384cd12",
                            Apellidos = "Sarmiento",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Alvaro Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "037a29bc-63c7-4476-8fb2-788fc5e13cff",
                            Apellidos = "Trump",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Eusebio Anabel Trump"
                        },
                        new
                        {
                            Id = "0042538c-db35-46b9-b7c8-03805369b7f9",
                            Apellidos = "Sarmiento",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Donald Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "00dfdbd7-7465-4258-a26a-54d0d1e48616",
                            Apellidos = "Maduro",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Donald Freddy Maduro"
                        },
                        new
                        {
                            Id = "01304e71-cae1-4131-a49e-9b3e6267fde7",
                            Apellidos = "Sarmiento",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Nicolás Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "021579d4-f3c3-44de-9b76-85827b222c49",
                            Apellidos = "Sarmiento",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Donald Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "0286473f-465a-4245-947e-0d6670be98f5",
                            Apellidos = "Sarmiento",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Alvaro Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "069a5b21-5b02-4196-ab7a-60e87e13f06f",
                            Apellidos = "Sarmiento",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Alba Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "06f4546c-559d-434f-a591-2208ebf177c7",
                            Apellidos = "Uribe",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Donald Rick Uribe"
                        },
                        new
                        {
                            Id = "0890692a-d141-4ed2-892b-b41b9dc64aff",
                            Apellidos = "Trump",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Eusebio Rick Trump"
                        },
                        new
                        {
                            Id = "0a67c27d-eaa9-4d04-8ebb-200d57a5436e",
                            Apellidos = "Ruiz",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Felipa Murty Ruiz"
                        },
                        new
                        {
                            Id = "0ae7a2e6-d87e-4b3c-9659-08b598e7d158",
                            Apellidos = "Ruiz",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Alvaro Silvana Ruiz"
                        });
                });

            modelBuilder.Entity("aspNet.Models.Asignatura", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CursoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = "d25873cb-c270-4357-8d48-e89ae9519a0e",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "989a2666-438a-47ae-bf14-8f2f86eca5c1",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "b868307a-fd8e-4725-8954-ce044cdd90f4",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "d0560e79-925e-444a-9bd0-03bc1a2a6af0",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "007e1fad-2144-46e3-8215-3499b04fa8c8",
                            CursoId = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Nombre = "Programacion"
                        },
                        new
                        {
                            Id = "ec86809e-b925-4274-ae49-0200a274ef36",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "442b6122-d398-4745-acf1-2fbf788b0249",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "d39f1e0e-654a-4044-9c2c-c10ccb338849",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "c66bab9d-187e-4e81-b9d5-c8a856863517",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "022a00c1-bf45-4394-9866-2a99fb393f92",
                            CursoId = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Nombre = "Programacion"
                        },
                        new
                        {
                            Id = "958ea3d8-c737-4428-aa1c-314abf3e5713",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "3367f033-3b63-40cd-a0d7-2a39b32403cb",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "244cac42-0b84-4770-9af4-c943aef811c6",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "976d5d78-2981-490e-aedf-2c3a27d75f9d",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "e5bc0dd8-874e-4ca7-9631-2741f6ecc18a",
                            CursoId = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Nombre = "Programacion"
                        },
                        new
                        {
                            Id = "21511106-0976-412c-a076-97baa264de6d",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "dfa00af3-ad64-42b3-a048-a2a0d24f2470",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "60b03ff4-20cc-4aec-9ae9-1c1d69f4fbb1",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "3a1accc4-d0a4-46e7-acd8-a1dc0ab4ba03",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "3c0de5a8-c1cd-4579-b885-9a45eaca0fe8",
                            CursoId = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Nombre = "Programacion"
                        },
                        new
                        {
                            Id = "fcf8e5de-606e-472a-a926-8cec011b3d3f",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "1cfc413d-d103-4b70-b10d-9f0d3aaca0be",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "c1e75b48-15ae-474a-9bb5-d50eabf002dd",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "ed73964e-8cba-4a72-a864-23251df4a428",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "ca49222c-baaf-4eb4-8d6f-b7db14340dc4",
                            CursoId = "20dcc888-28b2-4927-adb6-56402472d212",
                            Nombre = "Programacion"
                        });
                });

            modelBuilder.Entity("aspNet.Models.Curso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("EscuelaId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = "01a555ad-a26c-41c8-9dcf-472041e1abe0",
                            Direccion = "B/Progreso",
                            EscuelaId = "9faf5bea-9595-49d3-81c4-cf4e2a69cd94",
                            Jornada = 0,
                            Nombre = "101"
                        },
                        new
                        {
                            Id = "77ff663a-27b8-4fb0-b0f3-0d1aaafd5f9c",
                            Direccion = "Av. Santa Cruz",
                            EscuelaId = "9faf5bea-9595-49d3-81c4-cf4e2a69cd94",
                            Jornada = 0,
                            Nombre = "201"
                        },
                        new
                        {
                            Id = "6f0bbd65-010d-4e79-9da4-23a211d1457e",
                            Direccion = "C/Sucre",
                            EscuelaId = "9faf5bea-9595-49d3-81c4-cf4e2a69cd94",
                            Jornada = 0,
                            Nombre = "301"
                        },
                        new
                        {
                            Id = "5d567fb2-f4c0-42b2-8397-6e8b2f315b25",
                            Direccion = "C/ Aroma",
                            EscuelaId = "9faf5bea-9595-49d3-81c4-cf4e2a69cd94",
                            Jornada = 1,
                            Nombre = "401"
                        },
                        new
                        {
                            Id = "20dcc888-28b2-4927-adb6-56402472d212",
                            Direccion = "Av. Santa Cruz1",
                            EscuelaId = "9faf5bea-9595-49d3-81c4-cf4e2a69cd94",
                            Jornada = 1,
                            Nombre = "501"
                        });
                });

            modelBuilder.Entity("aspNet.Models.Escuela", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AnioCreacion")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoEscuela")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = "9faf5bea-9595-49d3-81c4-cf4e2a69cd94",
                            AnioCreacion = 2005,
                            Ciudad = "Santa Cruz",
                            Dirección = "Loc. Mineros",
                            Nombre = "Platzi School",
                            Pais = "Bolivia",
                            TipoEscuela = 1
                        });
                });

            modelBuilder.Entity("aspNet.Models.Evaluación", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AlumnoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AsignaturaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Nota")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("aspNet.Models.Alumno", b =>
                {
                    b.HasOne("aspNet.Models.Curso", "Curso")
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("aspNet.Models.Asignatura", b =>
                {
                    b.HasOne("aspNet.Models.Curso", "Curso")
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("aspNet.Models.Curso", b =>
                {
                    b.HasOne("aspNet.Models.Escuela", "Escuela")
                        .WithMany("Cursos")
                        .HasForeignKey("EscuelaId");

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("aspNet.Models.Evaluación", b =>
                {
                    b.HasOne("aspNet.Models.Alumno", "Alumno")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspNet.Models.Asignatura", "Asignatura")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("aspNet.Models.Alumno", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("aspNet.Models.Asignatura", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("aspNet.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("aspNet.Models.Escuela", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
