// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace aspNet.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    partial class EscuelaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aspNet.Models.Alumno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CursoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = "002cc428-2822-4014-b474-b1819c3fecc8",
                            Nombre = "Alvaro Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "00c129ec-e105-49cf-a1c1-a7005ed9d836",
                            Nombre = "Alvaro Anabel Maduro"
                        },
                        new
                        {
                            Id = "0114c2e4-6f03-4cb7-9983-9b67a7fb98a2",
                            Nombre = "Eusebio Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "0144d26b-927d-4ca2-80b2-54758e69c324",
                            Nombre = "Farid Silvana Herrera"
                        },
                        new
                        {
                            Id = "0153c8f8-76f8-4b38-92de-14006d3473a8",
                            Nombre = "Farid Silvana Uribe"
                        },
                        new
                        {
                            Id = "0247fa99-7472-43f8-b243-93627e4db6aa",
                            Nombre = "Nicolás Rick Ruiz"
                        },
                        new
                        {
                            Id = "03dab6de-3131-4428-a672-573019351d27",
                            Nombre = "Donald Rick Herrera"
                        },
                        new
                        {
                            Id = "05338187-f292-48d3-ac58-d25a124b19d8",
                            Nombre = "Felipa Anabel Toledo"
                        },
                        new
                        {
                            Id = "07333f4d-fec9-48a2-b422-ecbf4a452d93",
                            Nombre = "Donald Silvana Herrera"
                        },
                        new
                        {
                            Id = "0749d615-d5b3-4600-bffb-4beb0665c36d",
                            Nombre = "Farid Murty Herrera"
                        },
                        new
                        {
                            Id = "0756dd41-e5ac-4458-af34-4254461630d0",
                            Nombre = "Nicolás Rick Toledo"
                        },
                        new
                        {
                            Id = "07c4f5f5-e2d0-4de3-9c27-02dc3dcb0b45",
                            Nombre = "Donald Teodoro Maduro"
                        },
                        new
                        {
                            Id = "099c25c5-c110-458a-a3c3-c7511fabce3f",
                            Nombre = "Donald Teodoro Trump"
                        },
                        new
                        {
                            Id = "0a2e7781-2f54-464c-b43c-ace8f9301ac6",
                            Nombre = "Eusebio Silvana Herrera"
                        },
                        new
                        {
                            Id = "0ad66ea0-374e-409e-8fe2-8f43dcebecde",
                            Nombre = "Donald Teodoro Toledo"
                        },
                        new
                        {
                            Id = "0b1addf7-860e-44b3-a4d6-498a697c570f",
                            Nombre = "Eusebio Rick Sarmiento"
                        },
                        new
                        {
                            Id = "0b745d78-ae50-43d0-b46e-6aaba921c5b0",
                            Nombre = "Nicolás Teodoro Toledo"
                        },
                        new
                        {
                            Id = "0be9c451-c197-48db-ab25-9f81a1851999",
                            Nombre = "Eusebio Diomedes Herrera"
                        },
                        new
                        {
                            Id = "0c9d5e5d-3edb-47d1-ae41-54701fbe2097",
                            Nombre = "Nicolás Diomedes Maduro"
                        },
                        new
                        {
                            Id = "0cb813f3-deb9-4e6c-a95f-56f3368688e5",
                            Nombre = "Alvaro Silvana Trump"
                        },
                        new
                        {
                            Id = "0f2633ae-be23-4e76-b12c-0192f98c655c",
                            Nombre = "Nicolás Teodoro Trump"
                        },
                        new
                        {
                            Id = "0f427977-abab-43cd-9f46-27a5ca1c4980",
                            Nombre = "Eusebio Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "0f5a2d9c-83de-4cdb-b5c4-f3bf55624746",
                            Nombre = "Nicolás Teodoro Maduro"
                        },
                        new
                        {
                            Id = "103c30c4-3d01-46ac-9678-a8a4faf9245c",
                            Nombre = "Donald Rick Maduro"
                        },
                        new
                        {
                            Id = "10eda9b1-c13e-4dda-9b4d-c5e6d4d88339",
                            Nombre = "Felipa Anabel Ruiz"
                        },
                        new
                        {
                            Id = "119f6dd0-5814-4bdb-bb2c-4cb0b249d7e7",
                            Nombre = "Farid Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "11f824f1-032d-4ca7-ad18-097f7e71f536",
                            Nombre = "Felipa Silvana Ruiz"
                        },
                        new
                        {
                            Id = "12b1704d-1ad1-4249-a0d5-9956fee5fa6b",
                            Nombre = "Alvaro Anabel Ruiz"
                        },
                        new
                        {
                            Id = "13854e78-6648-4178-abab-d06b141455ec",
                            Nombre = "Felipa Diomedes Herrera"
                        },
                        new
                        {
                            Id = "13c4a71f-0604-4fd6-99a9-42f416a6cf7e",
                            Nombre = "Farid Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "14c427b1-97ac-4275-a6d4-4d58d3ea57a2",
                            Nombre = "Nicolás Anabel Ruiz"
                        },
                        new
                        {
                            Id = "15428c19-8a4f-4fca-8e46-5966b93f5b33",
                            Nombre = "Felipa Anabel Uribe"
                        },
                        new
                        {
                            Id = "166baaab-8a36-4016-9fdf-188f2d7ea563",
                            Nombre = "Nicolás Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "1727e0fe-8d7d-4659-ad41-772036c804f0",
                            Nombre = "Eusebio Diomedes Toledo"
                        },
                        new
                        {
                            Id = "180af402-aadf-47dc-b282-cac164270ea7",
                            Nombre = "Nicolás Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "1a1bec97-f68e-48a2-bb7f-6a4dcb148969",
                            Nombre = "Donald Diomedes Maduro"
                        },
                        new
                        {
                            Id = "1a720fbb-018a-413a-afa4-4a747af35acd",
                            Nombre = "Alvaro Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "1af239fe-0210-492a-b1f1-1cbe9826d902",
                            Nombre = "Donald Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "1bd7e2b6-91cd-4845-825a-c430a6aea561",
                            Nombre = "Eusebio Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "1c5952b7-79d4-482d-a7b9-1101bc3467bd",
                            Nombre = "Farid Diomedes Trump"
                        },
                        new
                        {
                            Id = "1d093437-e808-495e-b5f6-8cf6eb4d48b4",
                            Nombre = "Donald Rick Toledo"
                        },
                        new
                        {
                            Id = "1d1b4743-1297-4888-8612-aa90e972c1a2",
                            Nombre = "Alvaro Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "1d320692-13d5-4ace-9bdc-23e85082d61e",
                            Nombre = "Eusebio Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "1f1135a6-d788-4508-b8af-5d66031e9683",
                            Nombre = "Farid Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "1f6fd42d-7a23-4933-b148-19b4ca302b57",
                            Nombre = "Nicolás Anabel Herrera"
                        },
                        new
                        {
                            Id = "2161ad7f-8d15-4c95-8c91-2d4646d3f910",
                            Nombre = "Donald Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "216e478e-952e-47c7-b8ab-712a47ec0554",
                            Nombre = "Felipa Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "21ac1ff8-3b76-4928-b6f1-8f44a40bfac0",
                            Nombre = "Alba Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "21f2cfbe-6a79-46e6-9d96-652b02c61c7d",
                            Nombre = "Felipa Rick Trump"
                        },
                        new
                        {
                            Id = "225bef9d-65e9-4d88-bd9b-2db54e3dffd6",
                            Nombre = "Eusebio Freddy Herrera"
                        },
                        new
                        {
                            Id = "230d60cc-4679-4c07-8ecb-5b7ac291502d",
                            Nombre = "Farid Freddy Uribe"
                        },
                        new
                        {
                            Id = "248944b9-8af8-4690-a43e-e0138ad1ec26",
                            Nombre = "Alvaro Rick Sarmiento"
                        },
                        new
                        {
                            Id = "24a12e92-c567-4aed-aa57-60468f2d3fa8",
                            Nombre = "Nicolás Murty Uribe"
                        },
                        new
                        {
                            Id = "2639a9f3-1ac4-4d37-aea8-85ab3dcb0540",
                            Nombre = "Felipa Teodoro Maduro"
                        },
                        new
                        {
                            Id = "2675566b-da42-4c89-a1ec-d341ce3c3933",
                            Nombre = "Felipa Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "2804b41a-56c9-4dde-b11b-6b726ea48972",
                            Nombre = "Donald Anabel Toledo"
                        },
                        new
                        {
                            Id = "296629e7-6de5-4f59-9636-fab4569062e0",
                            Nombre = "Alvaro Freddy Uribe"
                        },
                        new
                        {
                            Id = "2a2820d7-d248-4f41-b836-e9106726798a",
                            Nombre = "Alba Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "2ad33b3d-2f5f-428b-b37d-7ed9e1054fdb",
                            Nombre = "Alvaro Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "2ae5f36f-daad-4c3d-8ae0-dd8321382d2a",
                            Nombre = "Farid Rick Uribe"
                        },
                        new
                        {
                            Id = "2c03ab9e-91bc-4a86-b831-60b8dd1a94f7",
                            Nombre = "Felipa Nicomedes Trump"
                        },
                        new
                        {
                            Id = "2c2f6fc9-4037-439d-be42-84bc65071b60",
                            Nombre = "Alba Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "2c4abe1e-d5f8-4c35-be9a-8ed16247dab4",
                            Nombre = "Eusebio Murty Sarmiento"
                        },
                        new
                        {
                            Id = "2c6245fd-b9e9-4558-86e1-e50f3a539664",
                            Nombre = "Alba Murty Ruiz"
                        },
                        new
                        {
                            Id = "2d7b08f1-cb90-4be1-be40-c6b27b0a5d3a",
                            Nombre = "Alba Rick Maduro"
                        },
                        new
                        {
                            Id = "2dde50da-d8ad-4e74-b8ff-5631c12e5b5f",
                            Nombre = "Farid Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "2e4c7b48-1856-4c32-997f-13b5eca34439",
                            Nombre = "Alvaro Anabel Uribe"
                        },
                        new
                        {
                            Id = "2ec9d348-33e7-4a37-8b31-88118e104fb4",
                            Nombre = "Nicolás Anabel Uribe"
                        },
                        new
                        {
                            Id = "2f776943-5cdf-4d37-b229-1cb860471ccb",
                            Nombre = "Eusebio Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "2fcc2c09-9ac9-43ff-8518-6f8e6359daae",
                            Nombre = "Alba Nicomedes Trump"
                        },
                        new
                        {
                            Id = "3017555d-39c3-47c7-828a-12f25ac2feee",
                            Nombre = "Felipa Silvana Herrera"
                        },
                        new
                        {
                            Id = "3054b8ee-257b-4e29-8e5d-7f9128006c78",
                            Nombre = "Felipa Freddy Toledo"
                        },
                        new
                        {
                            Id = "309dcf97-8ef0-47ac-8d30-652c1004c9c0",
                            Nombre = "Donald Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "31495ae1-7696-4024-83e4-c356d60401b2",
                            Nombre = "Donald Silvana Ruiz"
                        },
                        new
                        {
                            Id = "31cba438-ac4e-4627-b05c-76a5501e35d5",
                            Nombre = "Donald Anabel Uribe"
                        },
                        new
                        {
                            Id = "3200a5bc-0271-4ec2-aa99-26447dde43bc",
                            Nombre = "Alba Silvana Toledo"
                        },
                        new
                        {
                            Id = "32189f42-3541-4136-8195-49264c666f77",
                            Nombre = "Eusebio Rick Maduro"
                        },
                        new
                        {
                            Id = "33512144-16ea-4dbb-9397-57f1bd11921a",
                            Nombre = "Alba Rick Sarmiento"
                        },
                        new
                        {
                            Id = "336ecda1-115c-4eb5-a9a2-3d35209bc691",
                            Nombre = "Felipa Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "34cf8cf1-a96a-43b2-a7d3-df09f8974b2e",
                            Nombre = "Nicolás Silvana Trump"
                        },
                        new
                        {
                            Id = "3597c0bb-acb9-4768-8fcc-8ca28e890fb4",
                            Nombre = "Eusebio Rick Toledo"
                        },
                        new
                        {
                            Id = "35fd03af-6433-4827-bc9c-56f0533fc85f",
                            Nombre = "Nicolás Anabel Toledo"
                        },
                        new
                        {
                            Id = "37404462-2bc9-44d1-917f-2a47c22e4090",
                            Nombre = "Nicolás Murty Toledo"
                        },
                        new
                        {
                            Id = "38e96a3b-3b6e-4999-b524-de82d807b9e2",
                            Nombre = "Alvaro Teodoro Toledo"
                        },
                        new
                        {
                            Id = "39db0fbd-feda-4ea4-bdda-fe8c3243e223",
                            Nombre = "Alvaro Teodoro Maduro"
                        },
                        new
                        {
                            Id = "3a50cc4b-e486-4d3b-9477-9727a4bf7875",
                            Nombre = "Alba Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "3c1a9b04-44fd-44c2-a0a8-b3ba1f449983",
                            Nombre = "Nicolás Silvana Ruiz"
                        },
                        new
                        {
                            Id = "3d496379-1e05-4239-92a5-4411ca92fb3d",
                            Nombre = "Felipa Teodoro Toledo"
                        },
                        new
                        {
                            Id = "3dbc8f50-ccb0-4d13-88cd-56f446d130f8",
                            Nombre = "Eusebio Anabel Toledo"
                        },
                        new
                        {
                            Id = "3eab0d45-a195-4b62-8460-6d4a97c88609",
                            Nombre = "Alvaro Anabel Toledo"
                        },
                        new
                        {
                            Id = "42cbb9a7-8b98-47a2-ac51-fbcd713b060b",
                            Nombre = "Nicolás Nicomedes Trump"
                        },
                        new
                        {
                            Id = "43bd18ac-68c5-49d5-9da6-087ee4f53543",
                            Nombre = "Alba Teodoro Maduro"
                        },
                        new
                        {
                            Id = "443f5648-a30b-4107-a1a6-fec3066802a8",
                            Nombre = "Alvaro Anabel Herrera"
                        },
                        new
                        {
                            Id = "444cb612-1219-486a-a7a0-32cd5ec7b8ae",
                            Nombre = "Nicolás Murty Ruiz"
                        },
                        new
                        {
                            Id = "4468b48a-9c8e-42fa-9583-722ca33f5928",
                            Nombre = "Alba Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "449d5902-f70d-4227-9ca5-f494e4f5fa9f",
                            Nombre = "Donald Silvana Trump"
                        },
                        new
                        {
                            Id = "44c7e47b-11e5-4242-9216-e34cfb9df2cd",
                            Nombre = "Nicolás Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "460dedf3-cae0-432c-b226-c2536ea4bb80",
                            Nombre = "Eusebio Murty Herrera"
                        },
                        new
                        {
                            Id = "4646f247-ade5-4e9d-ac90-6032b7b5fcbd",
                            Nombre = "Farid Rick Toledo"
                        },
                        new
                        {
                            Id = "466187fb-2b1d-4dfa-aeed-6c89f41cac1e",
                            Nombre = "Alba Anabel Uribe"
                        },
                        new
                        {
                            Id = "4863e991-db8c-4a3c-8a54-9a9431e87def",
                            Nombre = "Farid Murty Ruiz"
                        },
                        new
                        {
                            Id = "4869f347-5d83-404b-9ee6-58e3d7e1603c",
                            Nombre = "Nicolás Teodoro Herrera"
                        },
                        new
                        {
                            Id = "491e5285-bd98-4e47-b0f2-02b77b6f7d6e",
                            Nombre = "Eusebio Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "49d39de4-41fd-4f68-9951-36a6a6d7d5ed",
                            Nombre = "Alba Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "4bb50756-dd8f-4f47-b292-2fa3a5d4a872",
                            Nombre = "Alvaro Diomedes Uribe"
                        },
                        new
                        {
                            Id = "4bd81bab-ce09-492d-80bd-945f92807b00",
                            Nombre = "Alba Diomedes Maduro"
                        },
                        new
                        {
                            Id = "4e22c191-57e8-4c97-9cce-40b83c4c4eea",
                            Nombre = "Nicolás Diomedes Herrera"
                        },
                        new
                        {
                            Id = "4ec9477b-1459-4c43-9cd6-b8dc651789a4",
                            Nombre = "Alvaro Teodoro Trump"
                        },
                        new
                        {
                            Id = "4ef8b3ac-44e9-4020-83c7-5e9a110717fb",
                            Nombre = "Farid Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "4f4a05a9-49d2-42c2-8a78-9f92a85b1a70",
                            Nombre = "Nicolás Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "5091b4da-32a1-48aa-a9f1-cfe903847b20",
                            Nombre = "Donald Rick Sarmiento"
                        },
                        new
                        {
                            Id = "50bfa99f-abc7-4488-9d0c-00dce54fd165",
                            Nombre = "Alvaro Murty Uribe"
                        },
                        new
                        {
                            Id = "50fd05cf-1c3f-48b0-bd32-9a9cfc4f17a0",
                            Nombre = "Eusebio Anabel Trump"
                        },
                        new
                        {
                            Id = "5101e0c3-2fea-4770-9564-d96ae3651a41",
                            Nombre = "Donald Diomedes Uribe"
                        },
                        new
                        {
                            Id = "5143fa42-89da-48d1-a9bb-2da8ab69f107",
                            Nombre = "Farid Freddy Herrera"
                        },
                        new
                        {
                            Id = "516f98da-e172-4ea8-84e0-d1b666c94892",
                            Nombre = "Alba Freddy Trump"
                        },
                        new
                        {
                            Id = "518f8e29-05dc-4de9-85ef-2b6bd8a1a920",
                            Nombre = "Farid Silvana Trump"
                        },
                        new
                        {
                            Id = "526839a3-3e1c-42b9-ad28-dd642eea2cd3",
                            Nombre = "Donald Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "52aa6d54-0e80-422b-9b87-9ea5cd2a3c3e",
                            Nombre = "Alba Freddy Ruiz"
                        },
                        new
                        {
                            Id = "54240d58-e936-4738-9c2f-34d0429add9f",
                            Nombre = "Farid Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "54d0927f-18ba-45b9-9c4e-08c861fe70d5",
                            Nombre = "Farid Rick Maduro"
                        },
                        new
                        {
                            Id = "55035a71-d71f-4459-831d-07e5c5682738",
                            Nombre = "Alba Silvana Uribe"
                        },
                        new
                        {
                            Id = "5575c566-47f4-4d19-b2f3-395f34f40e27",
                            Nombre = "Alvaro Diomedes Trump"
                        },
                        new
                        {
                            Id = "5650fd35-d9e7-40e7-aff2-fda05013fa3f",
                            Nombre = "Farid Murty Maduro"
                        },
                        new
                        {
                            Id = "5663a935-a660-4f62-9944-cbc60e05c46a",
                            Nombre = "Eusebio Freddy Toledo"
                        },
                        new
                        {
                            Id = "58b8f494-4a68-40b2-9f88-60d35aa455f0",
                            Nombre = "Farid Teodoro Herrera"
                        },
                        new
                        {
                            Id = "5b7b7b4c-9d8f-47d6-8b86-952e05360517",
                            Nombre = "Nicolás Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "5be4ee14-525a-49c5-8e1f-166db399f2a7",
                            Nombre = "Alvaro Freddy Ruiz"
                        },
                        new
                        {
                            Id = "5c1d7c04-e798-4617-91d9-01b2fdc4ab9d",
                            Nombre = "Farid Murty Trump"
                        },
                        new
                        {
                            Id = "5c859352-76c7-478d-bad1-13d8002fe08f",
                            Nombre = "Nicolás Freddy Ruiz"
                        },
                        new
                        {
                            Id = "5c8cffe4-7aa3-4c29-a872-a13266b4e405",
                            Nombre = "Farid Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "5ce23c00-59b9-474a-9836-12195a98157e",
                            Nombre = "Felipa Silvana Trump"
                        },
                        new
                        {
                            Id = "5d18f0f7-cf1f-44ac-aae5-96629d6d29d7",
                            Nombre = "Farid Silvana Toledo"
                        },
                        new
                        {
                            Id = "5d28dd78-8126-4bc7-9f25-fe1cffe78992",
                            Nombre = "Alvaro Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "5f1fbfd4-5090-4a3b-a115-0c7f87cb5610",
                            Nombre = "Nicolás Rick Trump"
                        },
                        new
                        {
                            Id = "5f32cd73-bead-4b7a-8e94-590b900d92a1",
                            Nombre = "Donald Freddy Herrera"
                        },
                        new
                        {
                            Id = "60ad5f36-ba90-4012-a261-703313c51b0b",
                            Nombre = "Eusebio Freddy Uribe"
                        },
                        new
                        {
                            Id = "6172eb96-4f59-46c7-b347-80540eda3be3",
                            Nombre = "Donald Anabel Maduro"
                        },
                        new
                        {
                            Id = "617be189-54cb-41f9-91a5-78b8cc628607",
                            Nombre = "Nicolás Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "628c530d-2f9e-44e0-a012-b494e02cda12",
                            Nombre = "Alvaro Teodoro Uribe"
                        },
                        new
                        {
                            Id = "641f326f-f1df-4b53-ab28-b81d04571ff9",
                            Nombre = "Eusebio Diomedes Maduro"
                        },
                        new
                        {
                            Id = "64302701-1e60-439c-a0ff-93af9f78877e",
                            Nombre = "Felipa Freddy Uribe"
                        },
                        new
                        {
                            Id = "64b57161-6db0-45cd-ab0b-fc0aee1002ff",
                            Nombre = "Eusebio Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "65084cf0-ee2f-49a3-b83b-2b3332a6c4f2",
                            Nombre = "Farid Diomedes Toledo"
                        },
                        new
                        {
                            Id = "65d5707b-030b-458a-8c62-d5afac855e6d",
                            Nombre = "Felipa Silvana Toledo"
                        },
                        new
                        {
                            Id = "67141c65-9ed9-48ac-bbb1-b161910303b6",
                            Nombre = "Donald Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "67719480-53b5-4707-a720-45c0c3a9698e",
                            Nombre = "Alba Murty Uribe"
                        },
                        new
                        {
                            Id = "68787136-3066-4693-9feb-5b11e676e8a6",
                            Nombre = "Eusebio Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "69a7b835-82dd-47f8-9564-a1c387e63148",
                            Nombre = "Farid Rick Trump"
                        },
                        new
                        {
                            Id = "69c656bb-7c52-47db-9832-b013be0b6662",
                            Nombre = "Farid Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "69c6e85d-0191-4045-9686-b47b9e20ca07",
                            Nombre = "Alba Rick Uribe"
                        },
                        new
                        {
                            Id = "6a101a50-b468-4f48-a935-863b1ca231a9",
                            Nombre = "Donald Rick Uribe"
                        },
                        new
                        {
                            Id = "6a8a3186-9ee1-46e4-8805-66f2957dddf4",
                            Nombre = "Felipa Rick Herrera"
                        },
                        new
                        {
                            Id = "6accbff0-549c-4b34-991e-521c0cd66d96",
                            Nombre = "Nicolás Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "6afd584c-2970-43da-b565-5c2ee1b72308",
                            Nombre = "Felipa Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "6b0b676a-24f2-49d0-be97-dc4639fe706a",
                            Nombre = "Alba Anabel Herrera"
                        },
                        new
                        {
                            Id = "6c13dca5-e802-4dd1-a78c-28cc1e15f53f",
                            Nombre = "Donald Murty Ruiz"
                        },
                        new
                        {
                            Id = "6c50458b-2ee4-4df9-be16-ea454845a54f",
                            Nombre = "Donald Freddy Uribe"
                        },
                        new
                        {
                            Id = "6f516dd6-02b1-4909-81f1-6f1e0a010ab7",
                            Nombre = "Nicolás Silvana Herrera"
                        },
                        new
                        {
                            Id = "6fcf342c-840f-457d-8b29-c8d7b09b9b69",
                            Nombre = "Alba Murty Trump"
                        },
                        new
                        {
                            Id = "7004a5ec-979f-4c2e-a5b5-c62bb3de7675",
                            Nombre = "Alvaro Rick Toledo"
                        },
                        new
                        {
                            Id = "70f13387-1d5c-4aea-8940-8f0f84ae2cb5",
                            Nombre = "Alvaro Freddy Toledo"
                        },
                        new
                        {
                            Id = "71ae5c25-1215-4617-879b-2d68df67d1b6",
                            Nombre = "Farid Diomedes Uribe"
                        },
                        new
                        {
                            Id = "71f01903-fd28-43cd-8121-07a175876e9d",
                            Nombre = "Alba Freddy Herrera"
                        },
                        new
                        {
                            Id = "721aa471-21fc-4a18-b6ac-219dfb4faa17",
                            Nombre = "Eusebio Silvana Maduro"
                        },
                        new
                        {
                            Id = "721eb9b6-d3f9-4728-be7c-44083dbcb856",
                            Nombre = "Alvaro Rick Uribe"
                        },
                        new
                        {
                            Id = "723e3c91-2b46-4bad-9114-911eb64afc97",
                            Nombre = "Alba Freddy Maduro"
                        },
                        new
                        {
                            Id = "72d271be-7e2a-49d1-83ec-926f0d99aef2",
                            Nombre = "Alba Anabel Trump"
                        },
                        new
                        {
                            Id = "72e0d0a3-0304-4b58-9745-f268cd1ac15a",
                            Nombre = "Alvaro Murty Sarmiento"
                        },
                        new
                        {
                            Id = "7341af54-46aa-4029-a16e-5e2d5a693a0f",
                            Nombre = "Nicolás Teodoro Uribe"
                        },
                        new
                        {
                            Id = "7346ca12-e8c4-41f3-a359-80ac729e6e56",
                            Nombre = "Alvaro Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "73500f57-2f06-48ef-bfbb-614bdf9e4005",
                            Nombre = "Alba Teodoro Toledo"
                        },
                        new
                        {
                            Id = "73dfb76a-b9cc-4ab1-b0ff-df69d0158d7e",
                            Nombre = "Eusebio Diomedes Uribe"
                        },
                        new
                        {
                            Id = "74d49ac6-1525-4933-8d67-58eec86c919e",
                            Nombre = "Alba Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "754a48e2-0912-4076-8eb1-5dfc3bc6d34d",
                            Nombre = "Alvaro Teodoro Herrera"
                        },
                        new
                        {
                            Id = "754d3a1c-c8ca-4c2f-80ad-ef39b54a00ad",
                            Nombre = "Eusebio Rick Ruiz"
                        },
                        new
                        {
                            Id = "76946e33-76ca-4bd4-b08c-7da6c56fe503",
                            Nombre = "Donald Nicomedes Trump"
                        },
                        new
                        {
                            Id = "776b4e01-cfbb-4ca8-95e2-8d68ca791497",
                            Nombre = "Donald Silvana Toledo"
                        },
                        new
                        {
                            Id = "78533a26-4ec6-4582-88dd-650cf9c84539",
                            Nombre = "Felipa Rick Sarmiento"
                        },
                        new
                        {
                            Id = "79350069-fa9b-4f43-9800-e4158d12d679",
                            Nombre = "Farid Murty Uribe"
                        },
                        new
                        {
                            Id = "79c7bbda-894d-4ffa-97a7-f5890ede674e",
                            Nombre = "Farid Freddy Maduro"
                        },
                        new
                        {
                            Id = "7b71ab68-0796-4d15-9efa-75c972b28c4d",
                            Nombre = "Eusebio Freddy Maduro"
                        },
                        new
                        {
                            Id = "7baf7e91-9ccb-4eb6-8bb2-2cf0c3412b54",
                            Nombre = "Felipa Diomedes Trump"
                        },
                        new
                        {
                            Id = "7c3768a4-512d-4949-a7f4-8ccc8db44bfc",
                            Nombre = "Alvaro Murty Ruiz"
                        },
                        new
                        {
                            Id = "7c6fe38f-9df4-422f-a3fd-f879f188ba65",
                            Nombre = "Eusebio Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "7c9833b9-6271-42d1-97ec-752130912d66",
                            Nombre = "Farid Teodoro Maduro"
                        },
                        new
                        {
                            Id = "7d406e8a-1454-4f9f-b78f-f416e1e18fc6",
                            Nombre = "Donald Diomedes Trump"
                        },
                        new
                        {
                            Id = "7dc5e523-39fd-4ebc-8a74-a34bb677b60f",
                            Nombre = "Alvaro Murty Herrera"
                        },
                        new
                        {
                            Id = "7f0188c4-7954-42e9-9773-64f0a8088521",
                            Nombre = "Farid Freddy Ruiz"
                        },
                        new
                        {
                            Id = "80bfab9a-fcfc-425f-8d0d-a9880c579c43",
                            Nombre = "Farid Murty Toledo"
                        },
                        new
                        {
                            Id = "81b1ace7-65e6-409d-8c65-c1f37651c10b",
                            Nombre = "Nicolás Freddy Trump"
                        },
                        new
                        {
                            Id = "81e62fc5-847f-4be1-bda4-325248dddb40",
                            Nombre = "Donald Diomedes Herrera"
                        },
                        new
                        {
                            Id = "8336c7a8-9bbc-480f-8f8d-cf80d1a4786e",
                            Nombre = "Felipa Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "836d9ce7-c10d-4ad9-8f35-c76d1d498f1b",
                            Nombre = "Alba Silvana Herrera"
                        },
                        new
                        {
                            Id = "8372f2c7-e01f-4031-be62-9d751566ad35",
                            Nombre = "Felipa Diomedes Toledo"
                        },
                        new
                        {
                            Id = "84b87ba5-ae22-4638-af07-7293d4f71646",
                            Nombre = "Eusebio Murty Toledo"
                        },
                        new
                        {
                            Id = "85c939df-80c9-47cf-9e06-0055e8d26f5a",
                            Nombre = "Donald Murty Herrera"
                        },
                        new
                        {
                            Id = "85d3277a-0173-4531-a278-7793679219a2",
                            Nombre = "Nicolás Rick Herrera"
                        },
                        new
                        {
                            Id = "8654de05-9b99-4a59-82ca-400838ae5ae9",
                            Nombre = "Farid Teodoro Toledo"
                        },
                        new
                        {
                            Id = "86becddb-9417-4248-8486-6a15a3bbc8f1",
                            Nombre = "Felipa Freddy Herrera"
                        },
                        new
                        {
                            Id = "875bfdf1-bc2f-46ee-907f-e7698b689514",
                            Nombre = "Felipa Diomedes Uribe"
                        },
                        new
                        {
                            Id = "884bfd52-5662-4544-8d6e-22fd75af410f",
                            Nombre = "Nicolás Diomedes Toledo"
                        },
                        new
                        {
                            Id = "886fb413-c97d-4579-bbed-935a44e2eac9",
                            Nombre = "Felipa Rick Uribe"
                        },
                        new
                        {
                            Id = "88eba082-02e5-4d8a-a428-53632821a8c7",
                            Nombre = "Felipa Murty Uribe"
                        },
                        new
                        {
                            Id = "8916d78f-fa5a-40f4-908e-6538bdaa5477",
                            Nombre = "Felipa Teodoro Herrera"
                        },
                        new
                        {
                            Id = "8a357858-8f65-4b28-be25-ffc78bf25f58",
                            Nombre = "Donald Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "8a40bc89-4d47-4c2c-a088-1ea660d335fc",
                            Nombre = "Donald Teodoro Uribe"
                        },
                        new
                        {
                            Id = "8aaa35fd-6cc5-4cc8-b84a-53b4392fa935",
                            Nombre = "Eusebio Nicomedes Trump"
                        },
                        new
                        {
                            Id = "8b915698-e956-4076-90ce-abc6b58aab99",
                            Nombre = "Nicolás Murty Maduro"
                        },
                        new
                        {
                            Id = "8be5403e-5065-4aa5-a8d2-423559579b3e",
                            Nombre = "Donald Anabel Herrera"
                        },
                        new
                        {
                            Id = "8d0cdd5c-0b30-4757-9be2-6e2e53af77c0",
                            Nombre = "Alvaro Silvana Herrera"
                        },
                        new
                        {
                            Id = "8e6755f8-311a-4285-89af-4da374b4d923",
                            Nombre = "Felipa Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "8eb71e65-a08d-47ab-bc25-0040f308c2a7",
                            Nombre = "Felipa Anabel Trump"
                        },
                        new
                        {
                            Id = "8f1ba844-79c7-4953-b200-0730b40cd7b3",
                            Nombre = "Eusebio Diomedes Trump"
                        },
                        new
                        {
                            Id = "8f98783a-328a-454e-90fc-d959fcf095ed",
                            Nombre = "Donald Anabel Ruiz"
                        },
                        new
                        {
                            Id = "90e81a30-c3e0-4aa9-a37b-e27115ca2e3f",
                            Nombre = "Alvaro Rick Trump"
                        },
                        new
                        {
                            Id = "91e21a40-6781-43f4-a8ac-ec014b2ec46a",
                            Nombre = "Alba Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "921297f1-0262-45a2-afe4-2671ca967bfe",
                            Nombre = "Donald Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "9250d1e1-1c71-432c-9327-c0407e38a8ab",
                            Nombre = "Felipa Murty Sarmiento"
                        },
                        new
                        {
                            Id = "9292e2f8-abb8-4b52-aa1c-1322a99cf879",
                            Nombre = "Donald Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "950cdc12-13b8-4939-ad19-964cae2ec4bc",
                            Nombre = "Farid Teodoro Uribe"
                        },
                        new
                        {
                            Id = "9570b4b5-f708-4c28-97e1-0ac9e8873e0c",
                            Nombre = "Felipa Rick Maduro"
                        },
                        new
                        {
                            Id = "96144965-8ebf-44f4-ba23-1d2d58771a4a",
                            Nombre = "Alvaro Murty Trump"
                        },
                        new
                        {
                            Id = "96814ae7-4684-4180-a771-2d996634d7f4",
                            Nombre = "Farid Anabel Ruiz"
                        },
                        new
                        {
                            Id = "9933f624-2b0a-4a14-a752-a256123b109d",
                            Nombre = "Nicolás Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "9a76d0a2-d334-4466-8d8e-830d6581119d",
                            Nombre = "Alvaro Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "9a862ad5-e4bd-401e-89b6-031209ef3675",
                            Nombre = "Alba Teodoro Trump"
                        },
                        new
                        {
                            Id = "9af258e2-ef9d-44f2-af5c-e818820bcd4e",
                            Nombre = "Felipa Murty Ruiz"
                        },
                        new
                        {
                            Id = "9b32bfa4-f235-4d80-beb9-44a07f0aee63",
                            Nombre = "Farid Silvana Ruiz"
                        },
                        new
                        {
                            Id = "9b38782e-34b7-4cbe-8a34-7f22d88c8844",
                            Nombre = "Felipa Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "9dd7ccbd-6810-424b-a2f5-97ceec160bca",
                            Nombre = "Eusebio Teodoro Uribe"
                        },
                        new
                        {
                            Id = "9e31cfd4-cf5f-442e-9bc4-196c60b3c279",
                            Nombre = "Donald Rick Ruiz"
                        },
                        new
                        {
                            Id = "9eaaa6a2-720f-4033-88cf-3126a4aa4b8c",
                            Nombre = "Farid Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "9eb72e10-9ee5-4a19-805e-de43f1af6dc8",
                            Nombre = "Farid Silvana Maduro"
                        },
                        new
                        {
                            Id = "9fa265cf-41c2-43d4-9ca1-2ff6ad4e2ad6",
                            Nombre = "Farid Freddy Toledo"
                        },
                        new
                        {
                            Id = "a11bfc20-548c-46a2-86f7-06cd73849045",
                            Nombre = "Nicolás Silvana Toledo"
                        },
                        new
                        {
                            Id = "a137c179-4f13-4450-b211-10aaa7d97007",
                            Nombre = "Alba Teodoro Uribe"
                        },
                        new
                        {
                            Id = "a23af219-e81f-4672-8690-02424374739f",
                            Nombre = "Nicolás Freddy Uribe"
                        },
                        new
                        {
                            Id = "a2bf1a70-7917-4b8e-913b-8be1156413f8",
                            Nombre = "Alvaro Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "a3ef4a77-593e-4a02-b7e7-bc95674871a2",
                            Nombre = "Donald Murty Toledo"
                        },
                        new
                        {
                            Id = "a5888307-ec33-4c37-8ad2-a25c90fabea6",
                            Nombre = "Eusebio Silvana Ruiz"
                        },
                        new
                        {
                            Id = "a754f1bd-edc1-4584-8b01-fc530c9b42a5",
                            Nombre = "Donald Freddy Toledo"
                        },
                        new
                        {
                            Id = "a762d9ef-992c-4f57-b4c6-8675f86af0d6",
                            Nombre = "Nicolás Diomedes Uribe"
                        },
                        new
                        {
                            Id = "a7c46159-1c21-4b51-b1fd-9c90165dbab0",
                            Nombre = "Felipa Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "a98943cb-6499-4fc8-a9de-eb56ff7b9efa",
                            Nombre = "Felipa Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "a98ca720-b4f2-44a9-b41a-9d74c06ffa25",
                            Nombre = "Eusebio Anabel Uribe"
                        },
                        new
                        {
                            Id = "aa459b7c-72a3-4089-9a57-476f3a49f8e9",
                            Nombre = "Alvaro Silvana Toledo"
                        },
                        new
                        {
                            Id = "ab074ea5-bd85-453d-a91d-320c19c59913",
                            Nombre = "Donald Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "abfc5c40-8a25-45dd-9fa6-7f65776b33a2",
                            Nombre = "Alvaro Diomedes Maduro"
                        },
                        new
                        {
                            Id = "acc16f1e-0bec-4e0f-980d-16552fd978f2",
                            Nombre = "Eusebio Teodoro Trump"
                        },
                        new
                        {
                            Id = "ad5748aa-698f-4790-9bdb-57a01b94406f",
                            Nombre = "Alba Murty Sarmiento"
                        },
                        new
                        {
                            Id = "adc08e84-c2da-416e-8744-36d4f647b77f",
                            Nombre = "Alvaro Murty Maduro"
                        },
                        new
                        {
                            Id = "ade6123f-5aff-4c91-aea3-778725c320d0",
                            Nombre = "Alvaro Diomedes Herrera"
                        },
                        new
                        {
                            Id = "ae7c5e51-2ba8-4953-9485-37ff83572ec4",
                            Nombre = "Felipa Rick Ruiz"
                        },
                        new
                        {
                            Id = "aeaa6971-93a4-4d14-885f-d50d7bcb08cd",
                            Nombre = "Nicolás Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "aee72652-cc66-4a8c-8120-351371b9b2d8",
                            Nombre = "Alvaro Rick Herrera"
                        },
                        new
                        {
                            Id = "af27ec7e-57cc-4547-90ba-dffe942de55d",
                            Nombre = "Eusebio Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "b09105c4-d138-4629-8981-98e1ddec0112",
                            Nombre = "Alvaro Silvana Ruiz"
                        },
                        new
                        {
                            Id = "b1303c16-1bcb-457e-8985-ddb55baa642e",
                            Nombre = "Eusebio Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "b1d0bde0-1040-48e7-abc6-4a1f600d8fb5",
                            Nombre = "Farid Rick Herrera"
                        },
                        new
                        {
                            Id = "b1db69e7-1027-4e79-8c7e-deedc380c78e",
                            Nombre = "Nicolás Rick Uribe"
                        },
                        new
                        {
                            Id = "b1e16e51-00d3-46c5-a3aa-5fa8779bb2b4",
                            Nombre = "Alba Diomedes Toledo"
                        },
                        new
                        {
                            Id = "b2d9dfa9-a99d-432d-b623-72e7049ac4a0",
                            Nombre = "Donald Freddy Ruiz"
                        },
                        new
                        {
                            Id = "b3128697-95f4-4ed3-a400-069825c974c8",
                            Nombre = "Farid Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "b4565bf5-2aea-4756-92c8-5dc59b5c4caa",
                            Nombre = "Eusebio Anabel Ruiz"
                        },
                        new
                        {
                            Id = "b4fdf3b8-0acc-48fd-98b4-1bb762cacd22",
                            Nombre = "Farid Anabel Toledo"
                        },
                        new
                        {
                            Id = "b55eb63f-91d3-459c-b3a8-045e7deb577f",
                            Nombre = "Felipa Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "b5afbd19-c382-4778-808d-4ddb46308e1d",
                            Nombre = "Nicolás Silvana Uribe"
                        },
                        new
                        {
                            Id = "b5e41a06-0976-4390-8491-080e57b268f8",
                            Nombre = "Donald Murty Trump"
                        },
                        new
                        {
                            Id = "b6c51b56-1134-4789-881f-53345fc5f332",
                            Nombre = "Donald Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "b730c58d-3462-43c5-881d-d4f6a805fe40",
                            Nombre = "Farid Anabel Uribe"
                        },
                        new
                        {
                            Id = "b8201423-db33-46c4-9625-d2d594045bf9",
                            Nombre = "Alba Anabel Ruiz"
                        },
                        new
                        {
                            Id = "b8aefbac-18f1-44b6-950e-97481f931371",
                            Nombre = "Alvaro Rick Maduro"
                        },
                        new
                        {
                            Id = "b9408eb2-c3d8-4a46-aed2-b2987ca178a5",
                            Nombre = "Donald Anabel Trump"
                        },
                        new
                        {
                            Id = "ba069f05-998c-4a76-8c05-e6514dd3e9eb",
                            Nombre = "Donald Freddy Trump"
                        },
                        new
                        {
                            Id = "ba6bf49c-9b4b-4eb4-a0d6-5f260b8919aa",
                            Nombre = "Alba Rick Herrera"
                        },
                        new
                        {
                            Id = "bb15609d-6795-40ec-9624-1001939f1bd1",
                            Nombre = "Eusebio Freddy Trump"
                        },
                        new
                        {
                            Id = "bb33f13c-0bdc-48d6-b8cc-e9ef586f0fe2",
                            Nombre = "Alba Murty Herrera"
                        },
                        new
                        {
                            Id = "bb70185b-f1fb-4738-bcaa-b3ad57611d58",
                            Nombre = "Nicolás Murty Trump"
                        },
                        new
                        {
                            Id = "bce25233-d483-4b23-a1f6-7a1d985d5b01",
                            Nombre = "Eusebio Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "bd3d49d3-caa4-476c-96fb-56c699829ade",
                            Nombre = "Nicolás Murty Sarmiento"
                        },
                        new
                        {
                            Id = "be4122b4-eac8-409b-b089-c9ceba777f66",
                            Nombre = "Felipa Freddy Ruiz"
                        },
                        new
                        {
                            Id = "be685948-9ef0-4f3b-a5b2-aabb3aa6ece2",
                            Nombre = "Donald Freddy Maduro"
                        },
                        new
                        {
                            Id = "beffeb31-d690-4e5d-9e3d-b9de131f8a53",
                            Nombre = "Eusebio Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "bf0f6c1c-4ad7-4b02-b88d-dafe4aeecafa",
                            Nombre = "Farid Rick Sarmiento"
                        },
                        new
                        {
                            Id = "c02442ae-949e-4546-a049-713ef25a826a",
                            Nombre = "Alba Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "c0926e7c-bef2-44bd-ad89-ff01852dbaee",
                            Nombre = "Alba Diomedes Trump"
                        },
                        new
                        {
                            Id = "c0a14e58-f077-42de-a582-9e183f1a4613",
                            Nombre = "Alba Diomedes Herrera"
                        },
                        new
                        {
                            Id = "c0f6ac63-7b82-42eb-89d6-533c09e06311",
                            Nombre = "Felipa Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "c1846bd3-bea3-4bd3-b2c7-f77ce1baae7b",
                            Nombre = "Donald Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "c1a49e2c-4396-45a9-8cff-270125b519ae",
                            Nombre = "Felipa Murty Maduro"
                        },
                        new
                        {
                            Id = "c2b2ba58-d954-4128-b3f1-c6944b9b32ab",
                            Nombre = "Farid Rick Ruiz"
                        },
                        new
                        {
                            Id = "c318c9e9-f5f1-4f4b-baf2-4859e62e412f",
                            Nombre = "Alvaro Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "c37f929f-0ddd-4e47-b6e1-6d8d6fe8f68c",
                            Nombre = "Nicolás Rick Sarmiento"
                        },
                        new
                        {
                            Id = "c43ac7be-3f2c-4997-b523-9d6c28535cad",
                            Nombre = "Donald Murty Maduro"
                        },
                        new
                        {
                            Id = "c53e81fc-94ef-452f-a625-c76d996b47b2",
                            Nombre = "Alvaro Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "c57eb917-c637-411b-b70f-4ba456edcb64",
                            Nombre = "Donald Teodoro Herrera"
                        },
                        new
                        {
                            Id = "c5c200b5-fc6a-46da-ad15-bb40370a1168",
                            Nombre = "Eusebio Murty Uribe"
                        },
                        new
                        {
                            Id = "c5f9ce03-85a8-472f-9148-e9675538f1a1",
                            Nombre = "Eusebio Silvana Trump"
                        },
                        new
                        {
                            Id = "c74efeac-87b1-43ab-a66b-f67c98829499",
                            Nombre = "Alvaro Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "c777e7cb-0960-4c5a-97c6-9e7eadf8bd5c",
                            Nombre = "Felipa Murty Herrera"
                        },
                        new
                        {
                            Id = "c77b75e8-7601-4bce-b141-00d2aac169c5",
                            Nombre = "Donald Diomedes Toledo"
                        },
                        new
                        {
                            Id = "c7be0c8a-db5c-4783-8a5d-f18bdb74884b",
                            Nombre = "Felipa Freddy Trump"
                        },
                        new
                        {
                            Id = "c7df90e5-46c8-404d-997c-ebc22e22c594",
                            Nombre = "Eusebio Teodoro Maduro"
                        },
                        new
                        {
                            Id = "c8063128-c285-42dc-a4a5-c844f126f97e",
                            Nombre = "Alba Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "c886877c-8216-4302-b317-5b7561ad9b65",
                            Nombre = "Nicolás Anabel Maduro"
                        },
                        new
                        {
                            Id = "c9098589-00cb-4496-b309-de170f44e734",
                            Nombre = "Nicolás Silvana Maduro"
                        },
                        new
                        {
                            Id = "cb9cabb3-80fa-4eb2-8e67-6720f8ff3809",
                            Nombre = "Farid Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "cbc4684e-7616-473f-8e88-0bca328da003",
                            Nombre = "Eusebio Teodoro Herrera"
                        },
                        new
                        {
                            Id = "cbeae485-5d2e-4168-975c-a9e61a74db6b",
                            Nombre = "Felipa Anabel Herrera"
                        },
                        new
                        {
                            Id = "cc63d2df-c4b9-4142-b70f-3e3aa458a40b",
                            Nombre = "Alvaro Freddy Maduro"
                        },
                        new
                        {
                            Id = "cce45def-9387-4d65-b034-21f6a512293d",
                            Nombre = "Nicolás Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "cd79e23e-4de5-45da-9362-8a7dd9f82f15",
                            Nombre = "Farid Anabel Herrera"
                        },
                        new
                        {
                            Id = "cd925f39-ca15-47f6-a12c-5a11aafe8635",
                            Nombre = "Alvaro Silvana Uribe"
                        },
                        new
                        {
                            Id = "cda53de1-66c9-426c-9957-890ece6b6e4b",
                            Nombre = "Donald Murty Sarmiento"
                        },
                        new
                        {
                            Id = "cde22778-09a6-4efd-8266-3b11d1c2fd6a",
                            Nombre = "Felipa Murty Toledo"
                        },
                        new
                        {
                            Id = "cde44cef-ab99-414c-ac96-19aa7c1985b1",
                            Nombre = "Eusebio Anabel Maduro"
                        },
                        new
                        {
                            Id = "ce5e5937-049a-4301-94eb-e7c930230a10",
                            Nombre = "Alvaro Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "cf04c72e-e02a-4a02-b92e-6fe965ae5b7a",
                            Nombre = "Alvaro Freddy Herrera"
                        },
                        new
                        {
                            Id = "cf89201d-d793-4429-94c6-208ca2b6eb57",
                            Nombre = "Farid Diomedes Herrera"
                        },
                        new
                        {
                            Id = "d07150a7-d3f2-4907-a577-ebd96dc1eca9",
                            Nombre = "Donald Murty Uribe"
                        },
                        new
                        {
                            Id = "d0cd1777-0884-4764-a4b9-90a16b78aed9",
                            Nombre = "Donald Rick Trump"
                        },
                        new
                        {
                            Id = "d0df0c9b-2c37-4d23-9952-59a2fa793bc2",
                            Nombre = "Alba Silvana Trump"
                        },
                        new
                        {
                            Id = "d113a8dc-9b16-4117-9d94-0b2780b163b0",
                            Nombre = "Eusebio Teodoro Toledo"
                        },
                        new
                        {
                            Id = "d18b8ee4-bd17-45af-b35d-5b03bd19e072",
                            Nombre = "Nicolás Rick Maduro"
                        },
                        new
                        {
                            Id = "d45d7782-f508-4d8b-9426-ae45f37169e5",
                            Nombre = "Nicolás Murty Herrera"
                        },
                        new
                        {
                            Id = "d4b7b029-b0ea-46a8-9504-c4091b9d13e9",
                            Nombre = "Felipa Rick Toledo"
                        },
                        new
                        {
                            Id = "d5086c2f-ba3d-410a-8044-da1e3dfbe901",
                            Nombre = "Felipa Teodoro Uribe"
                        },
                        new
                        {
                            Id = "d57aa44d-2ba6-4858-816c-bea08e3e82bf",
                            Nombre = "Felipa Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "d718503c-4355-4a4f-84b5-d777c7d86308",
                            Nombre = "Eusebio Anabel Herrera"
                        },
                        new
                        {
                            Id = "d7834195-401c-4169-b10e-acbe925c2054",
                            Nombre = "Alvaro Silvana Maduro"
                        },
                        new
                        {
                            Id = "d96e7c63-ea9e-424f-aefc-b0670fa40ecc",
                            Nombre = "Eusebio Rick Uribe"
                        },
                        new
                        {
                            Id = "d982f690-7838-43b0-8f54-a531e47675d6",
                            Nombre = "Felipa Diomedes Maduro"
                        },
                        new
                        {
                            Id = "d9f55ab1-64f4-4873-9c40-32a11a89dffb",
                            Nombre = "Farid Teodoro Trump"
                        },
                        new
                        {
                            Id = "da7271a0-2a17-4007-8a62-2e46b278e2d4",
                            Nombre = "Alba Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "db627ca2-45ba-4ee7-a93e-6560b1c55e65",
                            Nombre = "Alvaro Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "dc16fced-fdef-42a5-b675-0d238f7882f3",
                            Nombre = "Alba Silvana Maduro"
                        },
                        new
                        {
                            Id = "deff6dd8-7f0d-419d-8e64-5114b29feec2",
                            Nombre = "Alba Anabel Toledo"
                        },
                        new
                        {
                            Id = "e0c97e86-bc52-4a15-9d4d-2e361fe61f41",
                            Nombre = "Nicolás Diomedes Trump"
                        },
                        new
                        {
                            Id = "e32b5c79-ade6-4ab2-8b8f-e1c6293bbb20",
                            Nombre = "Nicolás Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "e3814bbe-5a14-4555-b8f4-c356c44abee1",
                            Nombre = "Alvaro Rick Ruiz"
                        },
                        new
                        {
                            Id = "e443d97a-0437-491a-8820-9cacbebbb1b5",
                            Nombre = "Donald Silvana Maduro"
                        },
                        new
                        {
                            Id = "e5024136-d70f-4c8d-90cf-73d4c9fb9e9e",
                            Nombre = "Donald Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "e55a426e-31ae-4bc9-b7d5-61db7d0e6b6a",
                            Nombre = "Eusebio Murty Ruiz"
                        },
                        new
                        {
                            Id = "e62d0643-a04e-4398-90dc-a78aa66be123",
                            Nombre = "Nicolás Freddy Toledo"
                        },
                        new
                        {
                            Id = "e6a84c20-1c7a-4986-830e-6d542f6b35d7",
                            Nombre = "Alba Freddy Uribe"
                        },
                        new
                        {
                            Id = "e85aac7c-cd85-40f6-8f5f-55ce8317d6a9",
                            Nombre = "Eusebio Freddy Ruiz"
                        },
                        new
                        {
                            Id = "e98fb2ad-d7bd-4b1b-9ad3-e4d25adf903c",
                            Nombre = "Farid Freddy Trump"
                        },
                        new
                        {
                            Id = "e9b5896d-18c5-427d-9ba0-604de90ffd1d",
                            Nombre = "Alba Diomedes Uribe"
                        },
                        new
                        {
                            Id = "e9c8d6d5-ce6e-4a70-b601-00c871dff186",
                            Nombre = "Farid Nicomedes Trump"
                        },
                        new
                        {
                            Id = "ea8186c5-8325-4c83-b18d-5fed766d37d0",
                            Nombre = "Nicolás Freddy Maduro"
                        },
                        new
                        {
                            Id = "ed75829e-fd82-4f2c-9a7e-ab197bd61ba8",
                            Nombre = "Eusebio Murty Maduro"
                        },
                        new
                        {
                            Id = "ef193da3-9bbe-4620-a4dd-627eb34117cd",
                            Nombre = "Eusebio Murty Trump"
                        },
                        new
                        {
                            Id = "efaaaaea-ab4c-4c0e-a341-78fc76f50816",
                            Nombre = "Nicolás Freddy Herrera"
                        },
                        new
                        {
                            Id = "efcd488d-06b6-4c62-b059-7044f07529af",
                            Nombre = "Farid Diomedes Maduro"
                        },
                        new
                        {
                            Id = "f00aa036-f1c4-4daf-a207-4ad2e965ca62",
                            Nombre = "Nicolás Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "f0164782-aa6a-4666-8838-8c9c4854561f",
                            Nombre = "Felipa Teodoro Trump"
                        },
                        new
                        {
                            Id = "f063fe2f-8ca7-4aa4-8417-dce43b6b75d0",
                            Nombre = "Alba Silvana Ruiz"
                        },
                        new
                        {
                            Id = "f07543c6-b184-4fba-ac27-c1a80ec8ee35",
                            Nombre = "Alvaro Murty Toledo"
                        },
                        new
                        {
                            Id = "f1437589-8693-4b80-85ca-6e387fd6f470",
                            Nombre = "Alba Anabel Maduro"
                        },
                        new
                        {
                            Id = "f163065b-104a-41e0-86ed-57ee70b7f53d",
                            Nombre = "Farid Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "f2590c97-8534-4516-93cc-a406eb07493f",
                            Nombre = "Farid Anabel Maduro"
                        },
                        new
                        {
                            Id = "f307972c-ae28-4bbd-b9c8-70bbc662305a",
                            Nombre = "Donald Silvana Uribe"
                        },
                        new
                        {
                            Id = "f320861f-62ee-468d-bcb2-ce60c136e8d7",
                            Nombre = "Farid Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "f3890c4a-09be-483c-b12b-27a30932d20e",
                            Nombre = "Alvaro Anabel Trump"
                        },
                        new
                        {
                            Id = "f3ac30b6-a815-461a-8c54-d9af2613b2ca",
                            Nombre = "Eusebio Rick Trump"
                        },
                        new
                        {
                            Id = "f4dffa8d-a36d-4d63-a00c-e21806e6564b",
                            Nombre = "Felipa Silvana Maduro"
                        },
                        new
                        {
                            Id = "f4f6dd0e-55de-4211-8ac6-3386e5540d6b",
                            Nombre = "Eusebio Silvana Uribe"
                        },
                        new
                        {
                            Id = "f50d4e4e-6f9f-432a-b8db-50a0b5127a2c",
                            Nombre = "Farid Murty Sarmiento"
                        },
                        new
                        {
                            Id = "f560999c-f094-430a-9303-de4b75fe2314",
                            Nombre = "Alba Teodoro Herrera"
                        },
                        new
                        {
                            Id = "f5bde9b6-6509-451e-99ec-5c04d7c06c87",
                            Nombre = "Alba Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "f5c62929-957e-455c-b5c5-64841d306b01",
                            Nombre = "Alba Rick Ruiz"
                        },
                        new
                        {
                            Id = "f621f222-b48d-441a-b455-04e0d30a97b8",
                            Nombre = "Felipa Silvana Uribe"
                        },
                        new
                        {
                            Id = "f702f2d6-93dc-498c-915e-9b4ee490fa50",
                            Nombre = "Eusebio Rick Herrera"
                        },
                        new
                        {
                            Id = "f7e28148-cc7e-4d14-a489-236743dc8caf",
                            Nombre = "Alba Rick Toledo"
                        },
                        new
                        {
                            Id = "f88a3791-50da-41b7-9cc4-75ffc8c5131b",
                            Nombre = "Nicolás Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "f92d4b53-bfcd-4373-8919-9f9dda01e236",
                            Nombre = "Alvaro Freddy Trump"
                        },
                        new
                        {
                            Id = "f934362e-f798-4e75-90db-7a884cac8bc2",
                            Nombre = "Alba Freddy Toledo"
                        },
                        new
                        {
                            Id = "f9668cde-7ee7-40b1-a955-f772852dc5fa",
                            Nombre = "Alba Murty Maduro"
                        },
                        new
                        {
                            Id = "fa23b6bf-2073-46d6-bc59-a84513544e16",
                            Nombre = "Eusebio Silvana Toledo"
                        },
                        new
                        {
                            Id = "faa9d784-1646-4711-b2b4-35241e4fd5e3",
                            Nombre = "Alvaro Diomedes Toledo"
                        },
                        new
                        {
                            Id = "faebafa6-0e5d-4086-9bf1-9e0cbdffc314",
                            Nombre = "Alba Rick Trump"
                        },
                        new
                        {
                            Id = "fbb6809a-8ab1-4b6f-b406-b1fe92e1592a",
                            Nombre = "Donald Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "fbd1913c-39bb-4051-81b0-031a84e6c7ca",
                            Nombre = "Felipa Anabel Maduro"
                        },
                        new
                        {
                            Id = "fc04cf62-cb57-4b49-be4b-3e297dd7992d",
                            Nombre = "Alvaro Nicomedes Trump"
                        },
                        new
                        {
                            Id = "fc8e91a4-254e-4680-983b-693e5be408f4",
                            Nombre = "Alba Murty Toledo"
                        },
                        new
                        {
                            Id = "fd12e6d7-cf34-4dd9-8359-295fde5e66ed",
                            Nombre = "Felipa Murty Trump"
                        },
                        new
                        {
                            Id = "fd3b89b3-1af0-4115-938a-d66259e19d11",
                            Nombre = "Felipa Freddy Maduro"
                        },
                        new
                        {
                            Id = "febd4204-594e-478e-8b38-f5cae3659ae9",
                            Nombre = "Felipa Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "fee0bfd3-42fd-4eca-98f8-16896134bf2f",
                            Nombre = "Nicolás Anabel Trump"
                        },
                        new
                        {
                            Id = "fefaf8c5-7abb-424c-8cf2-d3521c9d4ab2",
                            Nombre = "Alba Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "ff994e9c-2908-426a-bcae-2c271f539a8c",
                            Nombre = "Farid Anabel Trump"
                        });
                });

            modelBuilder.Entity("aspNet.Models.Asignatura", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CursoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = "b9f0297d-ffbd-42ff-98f3-dd728b9691ca",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "5406d145-2f8f-449c-8535-009837609cc8",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "6ecdb722-00ce-4378-ab01-2146fda28330",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "9aa230ca-b6a5-4388-94a1-f136c5cbf9b1",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "14c3ed8d-ec92-425d-995b-aa78687a9620",
                            Nombre = "Programacion"
                        });
                });

            modelBuilder.Entity("aspNet.Models.Curso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EscuelaId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("aspNet.Models.Escuela", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AnioCreacion")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoEscuela")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = "fe7df5cd-4571-4fa4-a646-ac2f299a817e",
                            AnioCreacion = 2005,
                            Ciudad = "Santa Cruz",
                            Dirección = "Loc. Mineros",
                            Nombre = "Platzi School",
                            Pais = "Bolivia",
                            TipoEscuela = 1
                        });
                });

            modelBuilder.Entity("aspNet.Models.Evaluación", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AlumnoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AsignaturaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Nota")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("aspNet.Models.Alumno", b =>
                {
                    b.HasOne("aspNet.Models.Curso", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("aspNet.Models.Asignatura", b =>
                {
                    b.HasOne("aspNet.Models.Curso", null)
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("aspNet.Models.Curso", b =>
                {
                    b.HasOne("aspNet.Models.Escuela", null)
                        .WithMany("Cursos")
                        .HasForeignKey("EscuelaId");
                });

            modelBuilder.Entity("aspNet.Models.Evaluación", b =>
                {
                    b.HasOne("aspNet.Models.Alumno", "Alumno")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspNet.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("aspNet.Models.Alumno", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("aspNet.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("aspNet.Models.Escuela", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
